const db = {
  novels: [
    {
      id: "n1",
      titleAr: "الهوبيت",
      titleEn: "The Hobbit",
      author: "J.R.R. Tolkien",
      descAr: "رجل صغير يركب رحلة مثيرة لاكتشاف عالم من الجنّ والكنوز والمخاطر التي تغيّر مسار حياته forever.",
      descEn: "A reluctant hero joins a perilous quest to reclaim a stolen treasure and discovers a world of dwarves, dragons, and adventure.",
      cover: "assets/images/The hobbit.webp",
      category: "Fantasy",
      rating: 4.30,
      chapters: 120,
      year: 1937,
      status: "Completed"
    },
    {
      id: "n2",
      titleAr: "1984",
      titleEn: "1984",
      author: "George Orwell",
      descAr: "في عالم مراقب، يحاول رجل عادي الحفاظ على إنسانيته أمام نظام قاسٍ يسيطر على كل شيء.",
      descEn: "In a world of constant surveillance, a man struggles to preserve his humanity under a brutal regime.",
      cover: "assets/images/1984 is now.webp",
      category: "Dystopian",
      rating: 4.20,
      chapters: 96,
      year: 1949,
      status: "Completed"
    },
    {
      id: "n3",
      titleAr: "كبرياء وتحامل",
      titleEn: "Pride and Prejudice",
      author: "Jane Austen",
      descAr: "رواية اجتماعية رومانسية عن التقدير والافتراضات التي تؤثر على العلاقات في عصرٍ من القيود الاجتماعية.",
      descEn: "A romantic social novel about first impressions, class, and the slow awakening of love between two strong-willed people.",
      cover: "assets/images/Pride and Prejudice.webp",
      category: "Romance",
      rating: 4.29,
      chapters: 61,
      year: 1813,
      status: "Completed"
    },
    {
      id: "n4",
      titleAr: "لقتل طائر بريء",
      titleEn: "To Kill a Mockingbird",
      author: "Harper Lee",
      descAr: "تتبع القصة نمو طفل في الجنوب الأميركي خلال سنوات التمييز، حين يواجه والده قضية عدالة غريبة.",
      descEn: "The story follows a child growing up in the American South as his father defends a Black man wrongly accused in a racially charged trial.",
      cover: "assets/images/To Kill.webp",
      category: "Drama",
      rating: 4.27,
      chapters: 31,
      year: 1960,
      status: "Completed"
    },
    {
      id: "n5",
      titleAr: "غاتسبي العظيم",
      titleEn: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      descAr: "تروي الرواية حلمًا أمريكيًا مشوّهًا عبر حياة غازي جاز، رجل مليء بالمال والأسرار.",
      descEn: "The novel explores the broken American Dream through the life of Jay Gatsby, a mysterious millionaire.",
      cover: "assets/images/The Great.webp",
      category: "Classic",
      rating: 3.95,
      chapters: 9,
      year: 1925,
      status: "Completed"
    },
    {
      id: "n6",
      titleAr: "الكثيب",
      titleEn: "Dune",
      author: "Frank Herbert",
      descAr: "في مستقبل بعيد، يواجه شاب مصيرًا سياسيًا ومذهلًا على كوكب صحراوي مليء بالسرّ والقدرة.",
      descEn: "In a distant future, a young nobleman is drawn into a political and spiritual struggle on a desert planet.",
      cover: "assets/images/Dune.webp",
      category: "Science Fiction",
      rating: 4.29,
      chapters: 60,
      year: 1965,
      status: "Completed"
    },
    {
      id: "n7",
      titleAr: "سيد الخواتم",
      titleEn: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      descAr: "أصدقاءٌ يهبطون إلى مغامرةٍ من أجل تدمير خاتمٍ يهدد العالم كله.",
      descEn: "A fellowship of heroes sets out to destroy a ring that threatens to dominate the world.",
      cover: "assets/images/The Lord of the rings.webp",
      category: "Fantasy",
      rating: 4.53,
      chapters: 117,
      year: 1954,
      status: "Completed"
    },
    {
      id: "n8",
      titleAr: "الحارس في حقل الشوفان",
      titleEn: "The Catcher in the Rye",
      author: "J.D. Salinger",
      descAr: "تروي الرواية رحلة شاب مضطرب في نيويورك، تبحث عن معنى للهوية والحرية.",
      descEn: "The novel follows a troubled teenager through New York as he searches for identity and meaning.",
      cover: "assets/images/The character.webp",
      category: "Coming-of-Age",
      rating: 3.82,
      chapters: 26,
      year: 1951,
      status: "Completed"
    },
    {
      id: "n9",
      titleAr: "الخيميائي",
      titleEn: "The Alchemist",
      author: "Paulo Coelho",
      descAr: "شابٌ يسعى وراء حلمه ويكتشف أن الطريق إلى الحقيقة قد يكون أعظم من الهدف نفسه.",
      descEn: "A shepherd boy follows his dream and learns that the journey itself may be the true treasure.",
      cover: "assets/images/The Alchemist.webp",
      category: "Philosophical",
      rating: 3.94,
      chapters: 40,
      year: 1988,
      status: "Completed"
    },
    {
      id: "n10",
      titleAr: "عدّاء الطائرة الورقية",
      titleEn: "The Kite Runner",
      author: "Khaled Hosseini",
      descAr: "رواية مؤثرة عن الصداقة والذنب والبحث عن الصفح في أفغانستان الحديثة.",
      descEn: "A moving story about friendship, guilt, and redemption set against the changing landscape of Afghanistan.",
      cover: "assets/images/The Kite Runner.webp",
      category: "Historical",
      rating: 4.39,
      chapters: 45,
      year: 2003,
      status: "Completed"
    },
    {
      id: "n11",
      titleAr: "الطريق",
      titleEn: "The Road",
      author: "Cormac McCarthy",
      descAr: "أب وابنه يسيران في عالمٍ مدمر بحثًا عن الأمل والنجاة.",
      descEn: "A father and son travel through a devastated world in search of hope and survival.",
      cover: "assets/images/The Road.webp",
      category: "Post-Apocalyptic",
      rating: 4.02,
      chapters: 73,
      year: 2006,
      status: "Completed"
    },
    {
      id: "n12",
      titleAr: "سارقة الكتب",
      titleEn: "The Book Thief",
      author: "Markus Zusak",
      descAr: "فتاة صغيرة تكتشف قوة الكلمات خلال الحرب العالمية الثانية في ألمانيا.",
      descEn: "A young girl discovers the power of words during World War II in Nazi Germany.",
      cover: "assets/images/The Book Thief.webp",
      category: "Historical",
      rating: 4.39,
      chapters: 50,
      year: 2005,
      status: "Completed"
    },
    {
      id: "n13",
      titleAr: "ألعاب الجوع",
      titleEn: "The Hunger Games",
      author: "Suzanne Collins",
      descAr: "في دولةٍ تسيطر عليها القوة، تضطر فتاة شابة إلى خوض مباريات قاسية من أجل البقاء.",
      descEn: "In a totalitarian nation, a young girl is forced to compete in a deadly televised spectacle to survive.",
      cover: "assets/images/The Hunger Games.webp",
      category: "Young Adult",
      rating: 4.35,
      chapters: 27,
      year: 2008,
      status: "Completed"
    },
    {
      id: "n14",
      titleAr: "سجلات نارنيا",
      titleEn: "The Chronicles of Narnia",
      author: "C.S. Lewis",
      descAr: "أطفال يكتشفون عالمًا سحريًا يربط أحلامهم بالمعركة ضد الشر.",
      descEn: "Children discover a magical world where their choices determine the fate of a realm threatened by evil.",
      cover: "assets/images/The Horse and His Boy.webp",
      category: "Fantasy",
      rating: 4.29,
      chapters: 84,
      year: 1950,
      status: "Completed"
    },
    {
      id: "n15",
      titleAr: "الغابة النرويجية",
      titleEn: "Norwegian Wood",
      author: "Haruki Murakami",
      descAr: "رواية عاطفية عن الحب والخسارة والبحث عن معنى الوجود في اليابان الحديثة.",
      descEn: "A lyrical novel about love, loss, and the search for meaning in modern Japan.",
      cover: "assets/images/Norwegian Wood.webp",
      category: "Literary",
      rating: 4.04,
      chapters: 60,
      year: 1987,
      status: "Completed"
    }
  ],
  manga: [
    {
      id: "m1",
      titleAr: "ون بيس",
      titleEn: "One Piece",
      author: "Eiichiro Oda",
      descAr: "قراصنة يبحثون عن جزيرة أحلامهم، بينما يكتشف مونكي دي لوفي عالمًا من المغامرات والبحر.",
      descEn: "A young pirate dreams of finding the ultimate treasure while exploring a vast world of adventures and danger.",
      cover: "assets/images/one piece.webp",
      category: "Manga",
      rating: 9.22,
      chapters: 1100,
      year: 1997,
      status: "Ongoing"
    },
    {
      id: "m2",
      titleAr: "ناروتو",
      titleEn: "Naruto",
      author: "Masashi Kishimoto",
      descAr: "شاب يحمل سرًا قويًا يسعى إلى أن يصبح نينجاً عظيماً ويحمي من يحبهم.",
      descEn: "A young ninja with a powerful secret seeks to become the strongest and protect the people he loves.",
      cover: "assets/images/Naruto.webp",
      category: "Manga",
      rating: 8.52,
      chapters: 700,
      year: 1999,
      status: "Completed"
    },
    {
      id: "m3",
      titleAr: "هجوم العمالقة",
      titleEn: "Attack on Titan",
      author: "Hajime Isayama",
      descAr: "في عالمٍ يعيش فيه البشر خلف جدرانٍ ضخمة، يواجه شابٌ حقائق مروعة عن الماضي.",
      descEn: "In a world where humanity survives behind massive walls, a young soldier uncovers devastating truths about the past.",
      cover: "assets/images/AOT.webp",
      category: "Manga",
      rating: 9.13,
      chapters: 139,
      year: 2009,
      status: "Completed"
    },
    {
      id: "m4",
      titleAr: "ديث نوت",
      titleEn: "Death Note",
      author: "Tsugumi Ohba & Takeshi Obata",
      descAr: "شاب يحصل على دفتر يقتل من يكتب اسمه فيه، ويقع في صراع مع قاضي شرس.",
      descEn: "A teenager gains a notebook that can kill anyone whose name is written inside, sparking a deadly game of cat and mouse.",
      cover: "assets/images/death note.webp",
      category: "Manga",
      rating: 8.62,
      chapters: 37,
      year: 2003,
      status: "Completed"
    },
    {
      id: "m5",
      titleAr: "سولو ليفلنج",
      titleEn: "Solo Leveling",
      author: "Chugong",
      descAr: "شاب ضعيف يشارك في معركةٍ قاتلة وينطلق نحو القمة في عالمٍ يزداد خطورةً كل يوم.",
      descEn: "A weak hunter enters a deadly world of monsters and powers that reshape his destiny.",
      cover: "assets/images/solo leveling.webp",
      category: "Manhwa",
      rating: 8.66,
      chapters: 200,
      year: 2018,
      status: "Ongoing"
    },
    {
      id: "m6",
      titleAr: "العالم بعد السقوط",
      titleEn: "The World After the Fall",
      author: "Sing Shong",
      descAr: "شاب يكتشف أن العالم حوله يتغير بما لا يُصدق أثناء رحلةٍ مليئة بالتهديدات.",
      descEn: "A young man discovers that the world around him has been transformed in startling ways during a dangerous journey.",
      cover: "assets/images/the world after the fall.webp",
      category: "Webtoon",
      rating: 8.15,
      chapters: 242,
      year: 2018,
      status: "Ongoing"
    },
    {
      id: "m7",
      titleAr: "سويت هوم",
      titleEn: "Sweet Home",
      author: "Carnby Kim",
      descAr: "رجلٌ يختبئ في مبنى سكني mientras يواجه وحوشًا ومخاوفًا لا نهاية لها.",
      descEn: "A man hides inside an apartment complex as terrifying monsters and human fears close in around him.",
      cover: "assets/images/sweet home.webp",
      category: "Webtoon",
      rating:8.55,
      chapters: 140 ,
      year: 2017,
      status: "Completed"
    },
    {
      id: "m8",
      titleAr: "الفول ميتال ألكيميست",
      titleEn: "Fullmetal Alchemist",
      author: "Hiromu Arakawa",
      descAr: "شقيقان يبحثان عن طريقة لاستعادة أجسادهما بعد تجربةٍ فاشلة في استدعاء الأرواح.",
      descEn: "Two brothers search for a way to restore their bodies after a failed attempt to bring back their mother.",
      cover: "assets/images/FullMetal Alchemist.webp",
      category: "Manga",
      rating: 9.10,
      chapters: 64,
      year: 2001,
      status: "Completed"
    },
    {
      id: "m9",
      titleAr: "تشينسو مان",
      titleEn: "Chainsaw Man",
      author: "Tatsuki Fujimoto",
      descAr: "شاب يُجبر على العيش بين الرعب والمال والقدرات الخارقة في عالمٍ متوحش.",
      descEn: "A young man is pulled into a brutal world of power, danger, and supernatural violence.",
      cover: "assets/images/Chainsaw Man.webp",
      category: "Manga",
      rating: 8.69,
      chapters: 97,
      year: 2018,
      status: "Ongoing"
    },
    {
      id: "m10",
      titleAr: "سباي x فاميلي",
      titleEn: "Spy x Family",
      author: "Tatsuya Endo",
      descAr: "عائلةٍ مصطنعة تتنقل بين الأسرار والمهام السرية ومرح الحياة اليومية.",
      descEn: "A fake family navigates secret missions, hidden identities, and everyday chaos with humor and heart.",
      cover: "assets/images/spyxfamily.webp",
      category: "Manga",
      rating: 8.52,
      chapters: 110,
      year: 2019,
      status: "Ongoing"
    }
  ]
};

// Expose data globally
window.readoraData = db;
